DROP TABLE IF EXISTS RESTAURANT;

CREATE TABLE RESTAURANT (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(250) NOT NULL,
  CITY VARCHAR(100) NOT NULL
);

INSERT INTO RESTAURANT (NAME, ADDRESS, CITY) VALUES
  ('Da Luigi', 'Via Verdi, 91B', 'Milano'),
  ('Pizza e fichi', 'Corso Italia, 21', 'Roma');